### ISSUE TITLE
Text Overflow when the text is large

### ISSUE THREAD

**Issue by sudipta1411** [vishwas-kr/Dashboard_App_UI#1]
Hello, as shown in the image, some text is overflowing.  

![unnamed](https://user-images.githubusercontent.com/1386911/189855953-06b38efb-f518-4d69-aecc-0554e96ac991.jpg)

I have wrapped the `Text` element within an `Expanded` as follows

    Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
            Expanded(flex: 1, 
                child: Text(
                        planing[index].heading,
                        style: const TextStyle(
                            fontWeight: FontWeight.bold,
                        ),
                        overflow: TextOverflow.ellipsis
                      )),
                      Text(
                        planing[index].subHeading,
                        style: const TextStyle(color: Colors.grey),
                      )
                    ],
           )

But it throws the following error

    The following assertion was thrown during layout:
    A RenderFlex overflowed by 4.0 pixels on the right.

    The relevant error-causing widget was:
    Row Row:file:///home/sudipta/SATHI/Dashboard_App_UI/lib/widgets/planing_grid.dart:23:22

    To inspect this widget in Flutter DevTools, visit:
    http://127.0.0.1:9101/#/inspector?uri=http%3A%2F%2F127.0.0.1%3A46497%2FiMD8ut7R2ts%3D%2F&inspectorRef=inspector-396

    The overflowing RenderFlex has an orientation of Axis.horizontal.
    The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
    black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
    Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
    RenderFlex to fit within the available space instead of being sized to their natural size.
    This is considered an error condition because it indicates that there is content that cannot be
    seen. If the content is legitimately bigger than the available space, consider clipping it with a
    ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
    like a ListView.
    The specific RenderFlex in question is: RenderFlex#ecf52 OVERFLOWING:
      creator: Row ← Padding ← DecoratedBox ← Container ← RepaintBoundary ← IndexedSemantics ←
        NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← KeyedSubtree ←
        SliverGrid ← MediaQuery ← ⋯
    parentData: offset=Offset(12.0, 12.0) (can use size)
    constraints: BoxConstraints(w=304.0, h=58.0)
    size: Size(304.0, 58.0)
    direction: horizontal
    mainAxisAlignment: spaceBetween
    mainAxisSize: max
    crossAxisAlignment: center
    textDirection: ltr
    verticalDirection: down

I am very new to flutter, so this might bea very trivial problem.

**Comment by vishwas-kr** [comment]
Thanks for reporting this issue. 
I have fixed this. I have used MediaQuery to fix this and make the text responsive. 

 * fontSize: MediaQuery.of(context).size.width * 0.035   "

you can also add 
* overflow: TextOverflow.ellipsis  property in TextStyle. 


for more info please look at [MediaQuery](https://api.flutter.dev/flutter/widgets/MediaQuery-class.h)

Thank you.

**Comment by sudipta1411** [comment]
Thanks

**Comment by sudipta1411** [comment]
Hello,
The problem is still there. The text is still overfowing. I have cloned the repo in my local machine and have run that.
